# Generated by Django 3.2 on 2022-11-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_element', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='classroom', max_length=255),
        ),
    ]
