# Generated by Django 3.2 on 2023-03-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_element', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(blank=True, default='#0000', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='exam_element.exam'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='grade',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
